name: Auto Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Auto Build in bubbles-wow/WSA-Modified
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          "https://api.github.com/repos/bubbles-wow/WSA-Modified/actions/workflows/auto_build_x64.yml/dispatches" \
          -d '{"ref": "main"}'
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          "https://api.github.com/repos/bubbles-wow/WSA-Modified/actions/workflows/auto_build_arm64.yml/dispatches" \
          -d '{"ref": "main"}'
