name: WSAUpdateChecker

on:
  workflow_dispatch:

  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 🏭
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: '3.x'

      - name: Install Ubuntu Dependencies 🧑‍🏭
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: e2fsprogs attr unzip qemu-utils python3-venv
          version: 1.0

      - name: Install Python dependencies
        run: 
          pip install requests

      - name: Check update
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.email "917749218@qq.com"
          git config --global user.name "bubbles-wow"
          python3 WSAUpdateChecker_workflow.py
        